[project]
name = "ros-humble"
# Just a convention, this is the same of the mutex package
version = "0.7.0"
description = "RoboStack repo for package ros-humble packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64", "win-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[tasks]
upload = "anaconda -t $ANACONDA_API_TOKEN upload"

[dependencies]
python = ">=3.11.0,<3.12"
rattler-build = ">=0.33"
anaconda-client = ">=1.12"

[feature.beta.pypi-dependencies]
# This is tipically the latest commit on rattler-build-humble branch
vinca = { git ="https://github.com/RoboStack/vinca.git", rev = "f6ce41dd4e485f3230a305b5672d1bac00dbe4cf" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
# vinca = { path = "../vinca", editable = true }

[feature.beta.tasks]
rename-file = { cmd ="cp vinca_linux_64.yaml vinca.yaml" }
generate-recipes = { cmd = "vinca -m", depends_on = ["rename-file"] }
remove-file = { cmd = "rm vinca.yaml", depends_on = ["generate-recipes"] }
build_additional_recipes = { cmd = "rattler-build build --recipe-dir ./additional_recipes -m ./conda_build_config.yaml --skip-existing", depends_on = ["remove-file"] }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml --skip-existing", depends_on = ["build_additional_recipes"] }

[environments]
beta = ["beta"]
